---
language:     ruby
bundler_args: --without metrics --without benchmarks
cache:        bundler
script:       bundle exec rake test:coverage:run
rvm:
  - '2.1'
  - '2.2'
  - ruby-head
  - rbx-2 --2.1
  - jruby-9.0.0.0
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
